<a href="https://colab.research.google.com/github/SPYACO-04/Machine-Learning/blob/main/Chisquare.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import seaborn as sns
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency

In [7]:
df = sns.load_dataset("titanic")
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [8]:
contingency_table = pd.crosstab(df['sex'], df['survived'])
contingency_table

survived    0    1
sex
female     81  233
male      468  109

In [9]:
chi2, p_value, dof, expected = chi2_contingency(contingency_table)

print(expected)

[[193.47474747 120.52525253]
 [355.52525253 221.47474747]]

In [12]:
print("Chi-squared statistic:", chi2)
print("P-value:", p_value)
print("Degrees of freedom:", dof)

Chi-squared statistic: 260.71702016732104
P-value: 1.1973570627755645e-58
Degrees of freedom: 1

In [13]:
alpha = 0.5

In [14]:
if p_value <alpha :
  print('we reject the null hypothesis yes thereis a significant relationship btw gender and surviving')
else:
  print('we accept the null hypothesis')

we reject the null hypothesis yes thereis a significant relationship btw gender and surviving